config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"
  get 'tagsearches/search', to: 'tagsearches#search'
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "search" => "users#search"
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :read_counts, dependent: :destroy
  
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  #  フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
  
# 検索方法分岐
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :authenticate_user!, only: [:show]

  def show
    @user = User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
    @books = @user.books
    @book = Book.new
    @today_book =  @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end
  
  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td>
          <% if current_user != user%>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>Name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>Introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>Follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>Followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>
<div class='row'>
  <% if current_user != user %>
    <td><%= render "relationships/btn", user: user %></td>
  <% else %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

app/views/users/_search.html.erb
<h4>検索結果</h4>
<table class="table">
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class="row">
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'searches/search' %>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$('#search_result').html("<%= j(render 'search', search_book: @search_book ) %>");

app/views/users/show.html.erb
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <% unless @user.id == current_user.id %>
  <% if (current_user.following? @user) && (@user.following? current_user)  %>
  <% if @isRoom == true %>
    <p class="user-show-room"><a href="/rooms/<%= @roomId %>">チャットへ</a>
  <% else %>
    <%= form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, value: @user.id %>
      <% end %>
      <%= f.submit "チャットを始める"%>
    <% end %>
  <% end %>
  <% end %>
<% end %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books, user: @user %>
      <h4 class="mt-4 font-weight-bold">投稿数の前日比・前週比</h4>
      <div class="table_width">
        <!--当日・前日・前日比を表示-->
        <table class="table table-bordered text-center">
          <thead>
          <tr>
            <th>今日の投稿</th>
            <th>昨日の投稿</th>
            <th>前日比</th>
          </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @today_book.count %></td>
    	        <td><%= @yesterday_book.count %></td>
    	        <% if @yesterday_book.count == 0 %>
    	          <td>前日の投稿はなし</td>
    	        <% else %>
    	          <td>
    	            <% @the_day_before =   @today_book.count / @yesterday_book.count  %>
    	            <%= (@the_day_before * 100).round %>%
    	          </td>
              <% end %>
            </tr>
          </tbody>
        </table>
          
        <!--今週・先日・先週比を表示-->
        <table class="table table-bordered text-center">
          <thead>
          <tr>
            <th>今週の投稿</th>
            <th>先週の投稿</th>
            <th>先週比</th>
          </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @this_week_book.count %></td>
    	        <td><%= @last_week_book.count %></td>
              <% if @last_week_book.count == 0 %>
    	          <td>先週の投稿はなし</td>
              <% else %>
                <td>
                  <% @the_week_before = @this_week_book.count / @last_week_book.count  %>
    	            <%= (@the_week_before * 100).round %>%
    	           </td>
              <% end %>
            </tr>
          </tbody>
        </table>
        
        <!--7日分の投稿数を表示-->
        <h4 class="mt-4 font-weight-bold">７日間分の投稿数</h4>
        <table class='table table-bordered text-center'>
          <thead>
            <tr> 
              <th>６日前</th>
              <th>５日前</th>
              <th>４日前</th>
              <th>３日前</th>
              <th>２日前</th>
              <th>１日前</th>
              <th>今日</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @books.created_6day_ago.count %></td>
              <td><%= @books.created_5day_ago.count %></td>
              <td><%= @books.created_4day_ago.count %></td>
              <td><%= @books.created_3day_ago.count %></td>
              <td><%= @books.created_2day_ago.count %></td>
              <td><%= @books.created_yesterday.count %></td>
              <td><%= @books.created_today.count %></td>
            </tr>
          </tbody>
        </table>
        <canvas id="myLineChart"></canvas>
        <script>
          $(document).on('turbolinks:load', function() {
            var ctx = document.getElementById("myLineChart");
            var myLineChart = new Chart(ctx, {
              type: 'line',
              data: {
                labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
                datasets: [
                  {
                    label: '投稿した本の数',
                    data: [
                      <%= @books.created_6day_ago.count %>,
                      <%= @books.created_5day_ago.count %>, 
                      <%= @books.created_4day_ago.count %>, 
                      <%= @books.created_3day_ago.count %>, 
                      <%= @books.created_2day_ago.count %>, 
                      <%= @books.created_yesterday.count %>, 
                      <%= @books.created_today.count %>
                    ],
                    borderColor: "rgba(0,0,255,1)",
                    backgroundColor: "rgba(0,0,0,0)",
                    tension: 0.4
                  }
                ],
              },
              options: {
                title: {
                  display: true,
                  text: '7日間の投稿数の比較'
                },
                responsive: true,
                scales: {
                  y:{
                    suggestedMin: 0,
                    suggestedMax: 10
                  },
                  x:{
                    stacked: true
                  },
                },
              }
            });
          });
        </script>
             <%= form_with url:user_search_path(@user), method: :get, local: false do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit '検索', class: "btn btn-primary" %>
      <% end %>

      <div id="search_result">
        <% if @search_book.present? %>
          <%= render 'search', search_book: @search_book %>
        <% end %>
      </div>
    </div>
  </div>
</div>